server:
  port: ${SERVER_PORT:9999}
  servlet:
    context-path: /dev-api
spring:
  main:
    banner-mode: off
  application:
    name: botAdmin
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    url: jdbc:postgresql://www.51ops.xyz:5432/admin
    driver-class-name: org.postgresql.Driver
  aop:
    auto: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: com.admin.entity
  check-config-location: true
  executor-type: reuse

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    root: info
    com.admin.mapper: debug
pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: false
  helper-dialect: postgresql