server:
  port: ${SERVER_PORT:9999}
  servlet:
    context-path: /dev-api
spring:
  main:
    banner-mode: off
  application:
    name: botAdmin
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    url: jdbc:log4jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgre}
    driver-class-name: net.sf.log4jdbc.DriverSpy
  aop:
    auto: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: com.admin.entity
  check-config-location: true
  executor-type: reuse
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-25.25logger{25}){cyan} %clr(==>:){faint} %m%n"
  level:
    root: error
    com.admin:
      config: info
      mapper: debug
    jdbc:
      audit: off
      sqlonly: off
      resultSet: off
      connection: off
      sqltiming: off
pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: false
  helper-dialect: postgresql