server:
  port: ${SERVER_PORT:9999}
  servlet:
    context-path: /dev-api
spring:
  main:
    banner-mode: off
  application:
    name: botAdmin
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgre}
    driver-class-name: org.postgresql.Driver
  redis:
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:123456}
    username: ${REDIS_USERNAME:redis}
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  aop:
    auto: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  type-aliases-package: com.admin.entity.database
  check-config-location: true
  executor-type: reuse
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(%-25.25logger{25}){cyan} %clr(:){faint} %m%n"
  level:
    root: info
    org: error
    com.alibaba: error
    com.admin.mapper: debug
    com.admin.controller: debug
pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: false
  helper-dialect: postgresql
management:
  endpoint:
    info:
      enabled: on
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/noAuth/actuator"